### ISSUE TITLE
Create automatic Health Checking for Mirrors

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch-site#61]
CentOS uses a script that checks mirrors once every X hours to determine if a repository is up to date using a timestamp that is generated when syncing from the master repository. 

This way old mirrors or malfunctioning mirrors can be automatically taken off the mirror list. 

This partially goes hand in hand with #60 in order to make sure users are served quickly and not pointed to a mirror that is out of date or offline.

**Comment by Anyon3** [comment]
The problem with the blackarch-site, for security reason and co... the dev should be made in bash and stay as most as possible, static. I could add a script  in extra/  using PHP that will do the work you ask but no chance for now to get a dynamic listing on the website

**Comment by PedroSFreitas** [comment]
@Anyon3 @jmdevince I think the solution to this is quite simple:
Whenever there is a push to the repository (adding new tools, updating, etc), there should be also a push (update) of a file called updated.txt (or whatever) containing a timestamp of the push (update).
Since all the mirrors will rsync it, all the mirrors will have that same file. We can then have a really small js code in the page to just display the mirrors that have the timestamp in the file exactly like the one in ours. So we won't need any code running on the server side, only the client; and since the implementation seems simple enough, I don't see any harm.

edit: not sure why this took so long to get more attention.

**Comment by PedroSFreitas** [comment]
@noptrix I remember we talked about it on IRC a few months ago, I'm not sure if you remember.
(please read my previous comment).

**Comment by noptrix** [comment]
any updates on this @PedroSFreitas ?

**Comment by PedroSFreitas** [comment]
@noptrix not yet, unfortunately. But leave this open, I will have more time in the next days to work on this (I will keep you posted, thanks and sorry).

**Comment by ikstream** [comment]
As there seems to be no update I am closing this issue
