### ISSUE TITLE
How to fix this i need your help

### ISSUE THREAD

**Issue by kravchenko21456** [BlackArch/blackarch-site#91]
xmessage
I can't find an app to set the wallpaper with. You can install one in many ways but i will give you some simple advice: install Eterm and you're set. Eterm provides Esetroot and thats a great wallpaper setter. I recommend you install the package provided by your distro

**Comment by PedroSFreitas** [comment]
wallpaper is set through `feh`: https://wiki.archlinux.org/index.php/feh
Since the installation process will install `blackarch-config-x11`, you should change this line: https://github.com/BlackArch/blackarch-config-x11/blob/master/xprofile#L4

I'm sure I've answered this question before somewhere.

@noptrix close (I have no permission in here)
